### ISSUE TITLE
Choose a different package

### ISSUE THREAD

**Issue by krzema12** [krzema12/snakeyaml-engine-kmp#155]
I had a case where I depended on snakeyaml-engine directly, and snakeyaml-engine-kmp transitively (via kaml). I was getting weird runtime issues due to a clash of classes: https://gist.github.com/krzema12/dbee67c1eedc3329c916a9460a7f1833

If we put snakeyaml-engine-kmp in a different Java package, it would have prevented this issue.

Ideas:
* `org.snakeyaml.engine` -> `org.snakeyaml.engine.kmp` - a minimal change, makes it easy to migrate to the KMP version
* `org.snakeyaml.engine` -> `it.krzeminski.snakeyamlenginekmp` or `it.krzeminski.snakeyaml.engine.kmp` - corresponds to the Maven group ID and the actual owner of the library

Considerations:
* it will be harder to sync changes from the parent repo automatically because the file location will change
* as it's a breaking change, we should publish it as 3.x.y, and wait until Kotlin 2.0 is out

**Comment by aSemy** [comment]
I agree, a new package would be best in v3.0.

I like `it.krzeminski.snakeyaml.engine.kmp`.


I have an idea to make it easier to migrate from SnakeJava to SnakeKMP: create typealiases for all SnakeJava types in a file with `package org.snakeyaml.engine` that point to the new SnakeKMP equivalents. They can be annotated with `@Deprecated` and have a `ReplaceWith()` with the new package. WDYT?

> it will be harder to sync changes from the parent repo automatically because the file location will change

Will that be a problem? The file locations are already different. `src/main/java/org/snakeyaml/engine` vs `src/commonMain/kotlin/`.

**Comment by krzema12** [comment]
> I have an idea to make it easier to migrate from SnakeJava to SnakeKMP (...)

Do you mean documenting this process as a hint for a consumer of the library, or would it involve adding some aliases to the library?

> Will that be a problem? The file locations are already different. `src/main/java/` vs `src/commonMain/kotlin/`.

Oh, right, so it's not a problem then (at least not a bigger one that it already is)!

**Comment by sschuberth** [comment]
For the record, we're hitting the same issue in a project that depends on JRuby (which uses SnakeYAML) and KAML.

> it will be harder to sync changes from the parent repo automatically because the file location will change

Just FYI, there is no strict requirement in Kotlin that the file system paths and package names match. Maybe it makes sense to deliberately violate that convention here.

**Comment by aSemy** [comment]
Thanks @sschuberth, conflict between SnakeJava and SnakeKMP is a really good point I hadn't considered.

I'll make a PR to change the package.

I also agree that it's nice that the package and file path don't need to be matched, so I'm happy to move the files too.


I won't do the typealiases change - it's a lot of hassle, and I don't think the benefit is _that_ significant.

**Comment by aSemy** [comment]
One problem with removing the leading directories is that IntelliJ still shows a warning if there's no `.kt` file to 'anchor' the package in the root `src/kotlin/` dir.

We could add a `commonMain/kotlin/base.kt` that is empty, except for `package it. krzeminski...`. But that's a bit odd/janky.
