### ISSUE TITLE
Build using Java8?

### ISSUE THREAD

**Issue by 4o4E** [krzema12/snakeyaml-engine-kmp#202]
I found that the dependency was built using Java11 when using Kaml, which makes it impossible for me to run apps that rely on this library on Java8

`java.lang.UnsupportedClassVersionError: it/krzeminski/snakeyaml/engine/kmp/exceptions/MarkedYamlEngineException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by krzema12** [comment]
Ack, will take a look likely tomorrow, and prepare a patch release.

**Comment by aSemy** [comment]
hi @4o4E, I'd like to find out more about why you need Java 8.

It's not so easy to support Java 8, because SnakeKMP has a dependency on a library that's compiled to Java 11.

Is updating to Java 11 possible in your situation?

**Comment by 4o4E** [comment]
> hi @4o4E, I'd like to find out more about why you need Java 8.
> 
> It's not so easy to support Java 8, because SnakeKMP has a dependency on a library that's compiled to Java 11.
> 
> Is updating to Java 11 possible in your situation?

i am a bukkit plugin developer. my plugin support 1.12-latest ver minecraft, but 1.12 can only use java8(not minectaft, bukkit's limit)

**Comment by krzema12** [comment]
I've asked the owner of our dependency to support Java 8: https://github.com/ethauvin/urlencoder/issues/18

**Comment by rbraeunlich** [comment]
Hi everyone,
I just saw that there's already a PR by @krzema12 https://github.com/krzema12/snakeyaml-engine-kmp/pull/203
Since his looks more advanced we might be able to merge our two PRs into one.

**Comment by rbraeunlich** [comment]
I merged @krzema12's changes. I hope the result makes sense 😅

**Comment by krzema12** [comment]
The fix is merged, we're going to release a new version within 2 days.

**Comment by krzema12** [comment]
3.0.3 is released: https://github.com/krzema12/snakeyaml-engine-kmp/releases/tag/v3.0.3
