### ISSUE TITLE
Add benchmarks to catch performance degradation on earlier stages

### ISSUE THREAD

**Issue by OptimumCode** [krzema12/snakeyaml-engine-kmp#208]
Based on #204 discussion it would be good to have a benchmark running as a part of the tests. It should help to catch any performance degradation before any of the actual users.

I can think of two options:

1. Create a benchmark for JVM that will compare performance for actual SnakeYaml and for this KMP implementation. The results for snakeyaml-engine-kmp MUST NOT be worse than SnakeYaml results with some delta in percentage. This benchmark can be created using [jmh](https://github.com/openjdk/jmh) and executed from tests using `org.openjdk.jmh.runner.Runner`.
2. Create a self-made "benchmark" that will be running for all supported platforms. We need to measure the performance for all platforms on the GitHub runner. After that, we can compare the results for each run with those values and fail tests if values are different for more than some percentage. The [kotlinx-resources](https://github.com/goncalossilva/kotlinx-resources) library can be used to read YAML files required for benchmarks.

There is also a [kotlinx-benchmark](https://github.com/Kotlin/kotlinx-benchmark) library but I don't see how it can be used here because there is no way to execute the generated benchmarks from the test (at least there is no official way to do that - all the generated classes as well as benchmark executors are marked with internal API annotation)

@krzema12 @aSemy What do you think about those options? Do you have any objections or suggestions? Maybe you can other options here

I would think that the second option is better - it provides measurements for all supported platforms and should help to notice any degradation that could be platform-specific.

**Comment by aSemy** [comment]
Thanks for making this issue!

Using JMH would be best. kotlinx-benchmark would work, and would be better because it would test non-JVM targets, but tbh the Gradle config is not very nice. (I'm working on fixing that, but it might take some time.) For now, just testing JVM with JMH would work.

I'd like to use a tool to be able to track and measure performance over time. This looks promising: https://github.com/benchmark-action/github-action-benchmark?tab=readme-ov-file

For simplicity, I'd say testing against SnakeJava isn't necessary. Obviously if there's significant performance problems they need to be investigated, but that doesn't require comparison against SnakeJava. Once we have performance testing we can focus on improving SnakeKMP as-is.

**Comment by OptimumCode** [comment]
Thank you @aSemy for pointing out that GitHub action. It indeed looks like something that can help with monitoring benchmark results.
I will try to setup the publication of the benchmark result in my repo and will share a link with the results.

Regarding benchmarking: I will try to set up benchmarks in the same project as the SnakeKMP but I am not sure if jmh plugin will work easily with KMP project. What do you think about extracting benchmarks into a separate sub-project? It will definitely simplify the benchmark setup

**Comment by aSemy** [comment]
A separate subproject is a great idea 👌

**Comment by aSemy** [comment]
[ReferencesTest.java](https://github.com/krzema12/snakeyaml-engine-kmp/blob/c50aed08cbb1aa2433550c60f6c289731e72dbbd/src/jvmTest/java/org/snakeyaml/engine/usecases/references/ReferencesTest.java#L94) would be good to convert to a performance test. Maybe not initially, but later.

So would the [YAML Test Suite tests](https://github.com/krzema12/snakeyaml-engine-kmp/blob/6a42df1df0498d1d56cd9329356482beb2683c52/src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/TestSuiteTests.kt#L13) - but that might be a significant amount of work, as there are a lot of tests.

**Comment by krzema12** [comment]
Done in https://github.com/krzema12/snakeyaml-engine-kmp/pull/215, thanks @OptimumCode!
