### ISSUE TITLE
Port "Emitter: remove unused code in prepareTagPrefix"

### ISSUE THREAD

**Issue by krzema12** [krzema12/snakeyaml-engine-kmp#284]
https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/62238f0804db8c499fccfb9df789b50eb35810b7

**Comment by krzema12** [comment]
This piece of code doesn't exist in the current revision under `main`:
https://github.com/krzema12/snakeyaml-engine-kmp/blob/d8160db9e364357c9de413f85622ca885516180c/src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/emitter/Emitter.kt#L287-L291

Perhaps depends on another commit to port.

**Comment by krzema12** [comment]
@aSemy I know it's been a long time ago, but do you happen to recall why we removed this piece of code when converting to Multiplatform?

https://github.com/krzema12/snakeyaml-engine-kmp/pull/48/files#r1890452116

<img width="541" alt="Screenshot 2024-12-18 at 16 43 25" src="https://github.com/user-attachments/assets/49fbb2a0-3341-46f0-90cc-a6edfe19efcf" />

I noticed it when trying to port a change from snakeyaml-engine. I thought that we somehow split this method, but I cannot find an equivalent functionality in another place of the Emitter. It also doesn't seem related to porting to Multiplatform. If we fail to recall why we made this change, I think we should reinstate this piece.

**Comment by aSemy** [comment]
My speculative explanation is that SnakeYAML was originally converted from PyYAML. Maybe SnakeYAML introduced a bug during this conversion, or PyYAML had to make a copy of the string because strings (or whatever datatype held the string data) in Python wasn't immutable. So this function made a copy for safety.
