### ISSUE TITLE
Publishing snapshots from main branch doesn't work

### ISSUE THREAD

**Issue by krzema12** [krzema12/snakeyaml-engine-kmp#304]
See e. g. https://github.com/krzema12/snakeyaml-engine-kmp/actions/runs/12362611636/job/34502277861

**Comment by krzema12** [comment]
@aSemy do you recall why we publish the artifacts to GitHub vs. Maven's snapshot repository? For the latter, we could reuse the logic we use for publishing the releases, and this way we could also test this logic with every push to main. Do you see some arguments against migration to this approach?

**Comment by aSemy** [comment]
We added GitHub branch publishing right at the start before Maven Central publishing was configured. It was easy to configure and set up, but it's a hack. It's a workaround for GitHub Packages forbidding anonymous access.

It can definitely be removed and replaced with Maven Central snapshots.

**Comment by krzema12** [comment]
Let's see if the release workflow used for releasing to Maven Central works if ran from the main branch: https://github.com/krzema12/snakeyaml-engine-kmp/actions/runs/12381982894/job/34561992660

Waiting for `krzeminski` dir in https://s01.oss.sonatype.org/content/repositories/snapshots/it/

**Comment by krzema12** [comment]
It worked (wrong URL above): https://oss.sonatype.org/content/repositories/snapshots/it/krzeminski/
So the next step is to hook this workflow so that it's called for every commit on `main`.

**Comment by aSemy** [comment]
I suggest we delete the `artifacts` branch.

https://github.com/krzema12/snakeyaml-engine-kmp/tree/artifacts

It takes up a significant amount of space (try downloading a zip of the repo!)

Theoretically some project could depend on it as a Maven repository, but I doubt it, and it should be easy for them to instead use Maven Central.

**Comment by krzema12** [comment]
Done, thanks!
