### ISSUE TITLE
Update to Kotlin 1.9

### ISSUE THREAD

**Issue by aSemy** [krzema12/snakeyaml-engine-kmp#46]
I am creating this issue to keep track of tasks that are dependent on Kotlin 1.9

- [ ] Re-enable Gradle config cache (disabled in #44)
- [ ] Remove `val readableError`, replace with `override val message` https://github.com/krzema12/snakeyaml-engine-kmp/pull/61

**Comment by krzema12** [comment]
https://github.com/krzema12/snakeyaml-engine-kmp/pull/80
